### ISSUE TITLE
StatsDWriter: given data too big

### ISSUE THREAD

**Issue by iliuta** [jmxtrans/embedded-jmxtrans#105]
I am trying to use StatsDWriter and for some metrics I get the following warning:

2015/08/05-11:01:01.339  WARN [jmxtrans-export-1] org.jmxtrans.embedded.output.StatsDWriter - Given data too big (115bytes) for the buffer size (93bytes), skip it: stats.sys.jvm.loc... 

The metric is the following:
stats.sys.jvm.localhost.mongodb.connection_pools.localhost.27017.55c1d0513e2a02c639c596e2.Statistics.MinSize:0|c

I tried to play with bufferSize parameter but the result is the same.

"outputWriters": [
        {
            "@class": "org.jmxtrans.embedded.output.StatsDWriter",
            "settings": {
                "host": "${statsd.host}",
                "port": "${statsd.port}",
                "namePrefix": "stats.",
                "enabled": "${statsd.enabled:true}",
                "bufferSize" : 1024
            }
        }
    ]

I am using embedded-jmxtrans 1.1.0.

**Comment by cyrille-leclerc** [comment]
Thanks @iliuta and sorry for the issue.

I definitely did not test with a so long metric name but I don't understand why this metric is discarded. 109 chars is not that big.

I'll test asap, not sure that i will have time this week :-(

Cyrille

**Comment by YannRobert** [comment]
Hi @iliuta does PR #105 help?
I suppose it does not fix the root cause that would be a network error.

**Comment by iliuta** [comment]
Sorry, I haven't tested it yet. I'll do it right now and I'll let you know.

**Comment by iliuta** [comment]
The warning disappeared. I think all is ok now.

**Comment by YannRobert** [comment]
:smiley:
