### ISSUE TITLE
How do I configure collection of the JMX metrics from several remote hosts protected with credentials?

### ISSUE THREAD

**Issue by imochurad** [jmxtrans/embedded-jmxtrans#126]
I would like to incorporate jmxtrans in my application that would connect to several nodes in cloud environment and fetch JMX enabled metrics. Is that doable via json configuration? If not, how this can be achieved via API? Thanks in advance.

**Comment by cyrille-leclerc** [comment]
Hello @imochurad , I do apologize, I have not seen your issue.

To collect metrics from remote JMX servers, please look at https://github.com/jmxtrans/jmxtrans/wiki .

For questions like this one, please use our google group: https://groups.google.com/forum/#!forum/jmxtrans
