### ISSUE TITLE
Escaping dot in resultAlias

### ISSUE THREAD

**Issue by philnate** [jmxtrans/embedded-jmxtrans#127]
I would like to query for a bunch of metrics which all share the same Type and some common name, e.g. I would have:

```
{
  "queries": [
    {
      "objectName": "my.mbean:name=cluster.*,*",
      "resultAlias": "%name%",
      "attributes": [
        "Value"
      ]
    }]
}
```

The metrics collected are supposed to be sent to graphite, but due to the `org.jmxtrans.embedded.ResultNameStrategy` the won't appear like _cluster.some.hierarchy_, rather than _cluster_some_hierarchy_. This is kind of breaking the graphite namespace as previously hierarchical metrics will share the same top level, as all levels are joined into one. This happens only if I use placeholders, if I would directly write the exact same name with dots, they're not replaced.
Would it be possible to have the dot replacement optional?

**Comment by philnate** [comment]
@cyrille-leclerc you consider this something to be changed in embedded-jmxtrans?

**Comment by cyrille-leclerc** [comment]
@philnate I do apologize, I didn't see your previous message. This seem to be a very good idea.

Did you have a proposal? 

I imagined to add a configuration attribute to `org.jmxtrans.embedded.QueryAttribute` and to add a configuration parameter on the query  `"resultNameStrategy":"dontEscapeDotsInObjectName"`.

Your query would look like:

```json
{
  "queries": [
    {
      "objectName": "my.mbean:name=cluster.*,*",
      "resultAlias": "%name%",
      "resultNameStrategy":"dontEscapeDotsInObjectName",
      "attributes": [
        "Value"
      ]
    }]
}
```

**Comment by philnate** [comment]
@cyrille-leclerc that looks good to me and is basically what I envisioned, maybe a shorter resultNameStrategy would be nice :)

**Comment by cyrille-leclerc** [comment]
Please propose a value ;-)

**Comment by philnate** [comment]
Wouldn't it be sufficent to have something like `dontEscapeDots`? As it looks to me if there's an alias used, it resolves the aliases and then escapes it. So I don't see it limited to the ObjectName. Now while I'm thinking about it, escape doesn't seem appropriate either, as we don't escape it rather we replace it. Maybe `dontReplaceDots`?

**Comment by cyrille-leclerc** [comment]
Thanks @philnate I'll review ASAP. Other reviews are of course more than welcome.

**Comment by philnate** [comment]
Sorry to bug again, I guess you had not yet time to review this, @cyrille-leclerc?

**Comment by cyrille-leclerc** [comment]
Sorry for the delay, merged

**Comment by cyrille-leclerc** [comment]
@philnate can you please update the documentation at https://github.com/jmxtrans/embedded-jmxtrans/wiki ?

**Comment by philnate** [comment]
I've updated the following pages:
* https://github.com/jmxtrans/embedded-jmxtrans/wiki/Configuration-sample
* https://github.com/jmxtrans/embedded-jmxtrans/wiki/Expression-Language

Please let me know if there's anything else I can help with. May I as well ask for an release of embedded-jmxtrans containing this change?

**Comment by cyrille-leclerc** [comment]
@philnate could you please test https://github.com/jmxtrans/embedded-jmxtrans/releases/tag/embedded-jmxtrans-1.2.0-beta-1 ?

**Comment by philnate** [comment]
@cyrille-leclerc works nicely.

**Comment by philnate** [comment]
Hi @cyrille-leclerc what's the status about releasing 1.2.0?

**Comment by cyrille-leclerc** [comment]
@philnate, I have a GPG signing key issue to upload 1.2.0 to oss.sonatype.org (I just changed my laptop). The artifact is available at https://github.com/jmxtrans/embedded-jmxtrans/releases/tag/embedded-jmxtrans-1.2.0 .

**Comment by cyrille-leclerc** [comment]
The deployment of 1.2.1 on MAven Central seem to have succeeded. I'll check in 10 hours.

https://github.com/jmxtrans/embedded-jmxtrans/releases/tag/embedded-jmxtrans-1.2.1

**Comment by philnate** [comment]
@cyrille-leclerc yes looks good. Thanks
