### ISSUE TITLE
Add "polling" feature for configuration file

### ISSUE THREAD

**Issue by rylarson** [jmxtrans/embedded-jmxtrans#70]
The use case is when you are fine tuning writing of queries, it would be really nice to be able to turn on "polling" of the configuration file, for the configuration to be picked up at runtime instead of just once at startup. This would be similar to the polling feature in logback. 

I will probably add this at some point, I just wanted to get the issue out here so we can see if there is any support for it.

**Comment by cyrille-leclerc** [comment]
Implemented in 1.0.14.

https://github.com/jmxtrans/embedded-jmxtrans/releases/tag/embedded-jmxtrans-1.0.14
