### ISSUE TITLE
Reuse outputwriter classes between jxmtrans, embedded-jmxtrans and maybe jxmtrans-agent

### ISSUE THREAD

**Issue by aadamovich** [jmxtrans/embedded-jmxtrans#74]
Is it correct assumption that jmxtrans and embedded-jxmtrans use different OutputWriter impementation that are not reusable? I don't see that embedded-jxmtrans depends on jmxtrans. Would it make sense to create a common core?

**Comment by cyrille-leclerc** [comment]
jmxtrans2 is intended to merge the different implementations. I'm closing the issue.

https://github.com/jmxtrans/jmxtrans2
