### ISSUE TITLE
Usage in Jetty embedded?

### ISSUE THREAD

**Issue by SaschaMoellering** [jmxtrans/embedded-jmxtrans#87]
Hi,

we want to use it in embedded Jetty, do you have a working example for that?

Thx,
Sascha

**Comment by gehel** [comment]
That's probably more a question for the [Google group](groups.google.com/forum/#!forum/jmxtrans), but have a look into the [integration tests](https://github.com/jmxtrans/embedded-jmxtrans/blob/master/src/test/java/org/jmxtrans/embedded/EmbeddedJmxTransIntegrationTest.java), that might give you some idea. If you have a Spring application, you might be more interested in the [Spring examples](https://github.com/jmxtrans/embedded-jmxtrans/blob/master/src/test/resources/org/jmxtrans/embedded/spring/test-spring-configuration-1.xml). There is also a [servlet listener](https://github.com/jmxtrans/embedded-jmxtrans/blob/master/src/main/java/org/jmxtrans/embedded/servlet/EmbeddedJmxTransLoaderListener.java) you might want to try. And of course, the [wiki](https://github.com/jmxtrans/embedded-jmxtrans/wiki) has some good documentation and examples.

If you want to add JmxTrans with zero integration with your application, have a look into [jmxtrans-agent](https://github.com/jmxtrans/jmxtrans-agent) or [jmxtrans standalone](https://github.com/jmxtrans/jmxtrans).

**Comment by cyrille-leclerc** [comment]
@SaschaMoellering Can we close the issue?

**Comment by SaschaMoellering** [comment]
Sure, you can close this case, no problem.

**Comment by cyrille-leclerc** [comment]
Thanks @SaschaMoellering
